apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: codegen-llamacpp-0612 
  janus-idp.io/tekton: codegen-llamacpp-0612
  backstage.io/kubernetes-id: codegen-llamacpp-0612
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: codegen-llamacpp-0612
resources: 
- application-dev.yaml