apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  labels: 
    app.kubernetes.io/instance: codegen-llamacpp-0612
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name:  codegen-llamacpp-0612
    app.kubernetes.io/part-of: codegen-llamacpp-0612  
  name: codegen-llamacpp-0612
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance:  codegen-llamacpp-0612 
  template:
    metadata: 
      labels:
        app.kubernetes.io/instance:  codegen-llamacpp-0612
    spec:
      containers:
      - env:
        - name: MODEL_ENDPOINT
          value: http://codegen-llamacpp-0612-model-server:8001
        image:  quay.io/yangcao/codegen:latest
        name: app-inference
        ports:
        - containerPort: 8501
        securityContext:
          runAsNonRoot: true